#!/bin/bash

# This script synchronizes all contents (-t full) or all subfolders (-t sub) of
# the given src_path into dst_path. By default, only subfolders are synchronized
# allowing for a more flexible approach where source doesn't have to completely
# match the destination.

set -eu

die() {
	echo "Not run: $1" >&2
	exit 0
}

rsync_exclude="$HOME/local/config/rsync_exclude"
# commented --checksum
rsync_opts="--archive --itemize-changes --update --delete"
src_path=""
dst_path=""
verbose=""
src_mounted=""
dst_mounted=""
type=0

while getopts "vt:s:d:m:n:" opt; do
	case $opt in
		s) src_path="$OPTARG" ;;
		d) dst_path="$OPTARG" ;;
        t) type="$OPTARG" ;;
		v) verbose="--verbose" ;;
        m) src_mounted="$OPTARG" ;;
        n) dst_mounted="$OPTARG" ;;
	esac
done

[ -d "$src_path" -a -d "$dst_path" ] || die "folders not ready, skipping: $src_path -> $dst_path"

[ -z "$src_mounted" ] \
    || mount | grep --word-regexp --quiet "$src_mounted" \
    || die "$src_mounted not mounted, skipping: $src_path -> $dst_path"

[ -z "$dst_mounted" ] \
    || mount | grep --word-regexp --quiet "$dst_mounted" \
    || die "$dst_mounted not mounted, skipping: $src_path -> $dst_path"

if [ "$type" = "sub" ]; then
    # Sync subfolders
    echo "# syncing subfolders from $src_path to $dst_path..."
    subprojects=$(find "$src_path" -mindepth 1 -maxdepth 1 -type d)
    for prj_dir in $subprojects; do
        prj_dir="$(basename $prj_dir)"  # get the folder name
        if ! grep -q $prj_dir $rsync_exclude; then
            echo "## syncing $prj_dir..."
            # --archive == -rlptgoD
            rsync $verbose $rsync_opts \
                --exclude-from="${rsync_exclude}" \
                "${src_path}/${prj_dir}/" \
                "${dst_path}/${prj_dir}"
        fi
    done
elif [ "$type" = "full" ]; then
    # Full sync
    echo "# syncing full from $src_path to $dst_path..."
    rsync $verbose $rsync_opts \
        --exclude-from=${rsync_exclude} \
        ${src_path}/ $dst_path
else
    echo "@ invalid type of sync: $type"
    exit 1
fi
