#!/bin/bash

set -eu

filename=""
verbose=""

while getopts vf: opt; do
	case $opt in
		f) filename="$OPTARG" ;;
		v) verbose="--verbose" ;;
	esac
done


BACKUP_FILE="${filename:-$(hostname)-system-$(date +%Y%m%d)-$(date +%H%M).tar}"

# dpkg
#######
PKG_DATA_FILE="dpkg.txt"

dpkg -l > $PKG_DATA_FILE
tar --create $verbose --file=$BACKUP_FILE $PKG_DATA_FILE
rm $PKG_DATA_FILE

# etc
#####
sudo tar --append $verbose --file=$BACKUP_FILE /etc
