#!/usr/bin/env python3

""" This script must be run inside safaribooks/Books. """

import pathlib
import re


DIR_RE = re.compile(r"(.+)\((\d+)\)$")


cwd = pathlib.Path.cwd()

for p in cwd.iterdir():
    if not p.is_dir():
        continue

    book_name, isdn = re.match(DIR_RE, p.name).group(1, 2)
    old_epub = p / f"{isdn}.epub"

    # lowercase
    new_epub_name = p.name.lower()

    # remove special characters
    new_epub_name = new_epub_name.translate({ord(i): None for i in "()-_"})

    # two or more contiguous spaces
    new_epub_name = re.sub(r'(\s)+', r'\1', new_epub_name)

    # replace spaces by dashes
    new_epub_name = new_epub_name.replace(' ', '-')

    new_epub = pathlib.Path(cwd / (new_epub_name + ".epub"))

    if old_epub.is_file():
        print(f"renaming {old_epub} to {new_epub}")
        old_epub.rename(new_epub)
