#!/bin/bash

echo "Installing apt packages..."
sudo apt-get -q --yes install \
	i3 \
	tmux \
	ripgrep \
	curl \
	arandr \
	pavucontrol \
	xclip \
	xsel

cd $HOME

mkdir -p opt

if [ -x "$(which rustup)" ]; then
	echo "Updating Rust/Cargo..."
	rustup update
else
	echo "Installing Rust/Cargo..."
	wget --quiet https://sh.rustup.rs -O - | sh -s -- --no-modify-path --profile minimal -y
fi

echo "Installing Rust tools..."

cargo install \
	hexyl \
	bat

[ -d "opt/nvim-linux64" ] && echo "Updating Neovim..." || echo "Installing Neovim..."

wget --directory-prefix=/tmp --quiet \
	https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
tar xzf /tmp/nvim-linux64.tar.gz -C opt
rm -f /tmp/nvim-linux64.tar.gz

wget --quiet --directory-prefix="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/autoload/" \
	https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Installing z.sh..."

wget --quiet https://github.com/rupa/z/raw/master/z.sh -O ~/opt/z.sh
