#!/bin/bash
set -u

FFX_INSTALL_PATH="/opt"

# Get real URL (302 redirect)
FFX_URL=$(curl -s 'https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=es-ES' | grep -o 'http.*bz2')

# Get current version
FFX_CUR=$(echo $FFX_URL | sed "s/.*firefox-\([0-9.]*[0-9]\).*/\1/")

# Get installed version
FFX_INS=$(firefox --version | cut -d" " -f3)

[ "$FFX_INS" == "$FFX_CUR" ] && \
    { echo "Installed version is updated ($FFX_INS)"; exit 0; }

# Download installation file
wget -N $FFX_URL

echo "Installing as root..."
sudo tar -jxvf firefox-${FFX_CUR}.tar.bz2 -C /opt

rm firefox-${FFX_CUR}.tar.bz2
